### ISSUE TITLE
Add additional logging to know that the component ran

### ISSUE THREAD

**Issue by winklerj** [blendededge/soap-component-oih#25]
There are scenarios where the component logs nothing and it's hard to determine if it ran or had an error outside of the try/catch

**Comment by winklerj** [comment]
@winklerj to validate whether this has already been done

**Comment by ryanlunka** [comment]
@winklerj we'll want to get this one confirmed and done before we start this SAP integration, now that we know it'll be via a SOAP web service.

**Comment by winklerj** [comment]
I believe this was the commit to add additional logging https://github.com/blendededge/soap-component-oih/commit/2b7c2a04a86409348b357164c321b5936cef830e on 10/23
