### ISSUE TITLE
Clean up logging and data emitting on SOAP component.

### ISSUE THREAD

**Issue by ryanlunka** [blendededge/soap-component-oih#26]

**Comment by winklerj** [comment]
Opened #29 to resolve this issue

**Comment by winklerj** [comment]
An updated component version has been released with additional logging and ensuring everything is inside the try/catch block https://github.com/blendededge/soap-component-oih/releases/tag/v1.3.3

**Comment by winklerj** [comment]
@ryanlunka What are the next steps

**Comment by ryanlunka** [comment]
Pushed version `1.3.3` to prod on 11/16.
